#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "atendimento-cliente"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "3value"

[assets]
directory = "./view-build"
binding = "ASSETS"

[deco]
workspace = "3value"
bindings = []
enable_workflows = true
local = false

[[deco.views]]
url = "https://atendimento-cliente.deco.page"
name = "homepage"
primary = true

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"